# Site settings
title: "森 爽真のポートフォリオ"
url: "https://Moriumaso.github.io"
baseurl: ""

# Minimal Mistakes Theme settings
minimal_mistakes_skin: "default"
remote_theme: "mmistakes/minimal-mistakes@4.24.0"

# Plugins (ビルドエラー対策)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jekyll-include-cache
